#!/usr/bin/env python3
"""Emit LaTeX result tables from completed runs.

    python scripts/make_tables.py --configs configs/qingdao.yaml configs/tdrive.yaml

Each fragment is a COMPLETE `tabular` environment, and main.tex pulls it in
with \\inputrows inside the float.  Emitting only the rows would read more
tidily, but \\input inside an alignment leaves a stray cell and a misplaced
\\bottomrule, so the alignment has to begin and end inside the same file.

Numbers are the mean +- std over the seeds that actually completed; the seed
count is written into the fragment as a comment so a half-finished sweep is
never silently read as a finished one.  A configuration that did not run prints
an em dash rather than being omitted, so the gap stays visible in the paper.
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path
from typing import Dict, List, Optional, Sequence

import numpy as np

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))

from hawformer.utils import get_logger, load_config          # noqa: E402

LOG = get_logger()

# Every ablation the paper defines, in the order it discusses them.  Tags that
# were never run are dropped from the table rather than shown as empty rows.
ABLATION = [
    ("no_micro", "w/o Micro"), ("no_high", "w/o High"), ("no_meso", "w/o Meso"),
    ("static_hier", "static-Hier"), ("hard_hs", "hard-$\\Hmat_s$"),
    ("identity_aff", "$\\boldsymbol{\\Lambda}=\\mathbf{I}$"),
    ("no_spectral", "w/o Spectral"), ("gamma1", "$\\gamma=1$"),
    ("no_wavelet", "w/o Wavelet"), ("no_dla", "w/o DLA"), ("no_gcn", "w/o GCN"),
    ("no_bank", "w/o Bank"), ("no_alt", "w/o Alt"),
]

PRETTY = {"qingdao": "Qingdao", "tdrive": "T-Drive", "chengdu": "Chengdu",
          "porto": "Porto", "synthetic": "Synthetic"}

HM = ("MAE", "RMSE", "WAPE")
METS = ("MAE", "RMSE", "WAPE", "MAPE")


def runs(root: Path, tag: str) -> List[Path]:
    return sorted(p for p in root.glob(f"{tag}_seed*") if (p / "report.json").exists())


def load(p: Path) -> dict:
    with open(p / "report.json") as f:
        return json.load(f)


def agg(root: Path, tag: str, keys: Sequence[str],
        path: Sequence[str] = ("overall",)) -> Optional[Dict]:
    rs = runs(root, tag)
    if not rs:
        return None
    out: Dict = {"_n": len(rs)}
    for k in keys:
        vals = []
        for p in rs:
            d = load(p)["test"]
            for step in path:
                d = d.get(step, {})
            if k in d and d[k] is not None:
                vals.append(float(d[k]))
        if vals:
            out[k] = (float(np.nanmean(vals)), float(np.nanstd(vals)))
    return out


def nd(m: str) -> int:
    return 3 if m in ("MAE", "RMSE") else 2


def cell(v, digits: int = 3) -> str:
    if v is None:
        return "---"
    m, s = v
    return f"${m:.{digits}f}\\pm{s:.{digits}f}$" if s > 0 else f"${m:.{digits}f}$"


def row(cells: Sequence[str]) -> str:
    return " & ".join(cells) + "\\\\"


def group_header(first: str, groups: Sequence[str], width: int,
                 lead: int, sub: Sequence[str]) -> List[str]:
    """Two-deck header: `groups` spanning `width` columns each, then `sub`."""
    return [
        first + " & " + " & ".join("\\multicolumn{%d}{c}{%s}" % (width, g)
                                   for g in groups) + "\\\\",
        " ".join("\\cmidrule(lr){%d-%d}" % (lead + 1 + width * i,
                                            lead + width * (i + 1))
                 for i in range(len(groups))),
        row([""] * lead + list(sub) * len(groups)),
    ]


def write(out: Path, name: str, spec: str, header: List[str],
          body: List[str], note: str = "") -> None:
    txt = ["% generated by scripts/make_tables.py -- do not edit by hand"]
    if note:
        txt.append(f"% {note}")
    txt += [f"\\begin{{tabular}}{{{spec}}}", "\\toprule"]
    txt += header + ["\\midrule"] + body + ["\\bottomrule", "\\end{tabular}"]
    (out / name).write_text("\n".join(txt) + "\n")
    LOG.info("wrote %s", out / name)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--configs", nargs="+", required=True,
                    help="one or more dataset configs; columns follow this order")
    ap.add_argument("--runs", default="runs")
    ap.add_argument("--out", default="tables")
    ap.add_argument("--tag", default="full")
    a = ap.parse_args()

    names = [load_config(c).get("name", Path(c).stem) for c in a.configs]
    disp = [PRETTY.get(n, n.capitalize()) for n in names]
    roots = [Path(a.runs) / n for n in names]
    out = Path(a.out)
    out.mkdir(parents=True, exist_ok=True)
    nds = len(roots)

    # ---- main comparison against the zero-training references --------------
    header = group_header("\\multirow{2}{*}{Model}", disp, 4, 1, METS)
    body = ["\\multicolumn{%d}{@{}l}{\\textit{Zero-training references}}\\\\"
            % (1 + 4 * nds)]
    for tag, label in (("ha", "Historical average"), ("copy_last", "Persistence")):
        cells = [label]
        for r in roots:
            d = agg(r, tag, METS)
            cells += [cell(d.get(m) if d else None, nd(m)) for m in METS]
        body.append(row(cells))
    body.append("\\midrule")
    cells, ns = ["\\textbf{HAWFormer}"], []
    for r in roots:
        d = agg(r, a.tag, METS)
        ns.append(d["_n"] if d else 0)
        cells += [cell(d.get(m) if d else None, nd(m)) for m in METS]
    body.append(row(cells))
    write(out, "table_main.tex", "@{}l" + " cccc" * nds, header, body,
          f"seeds per dataset: {dict(zip(names, ns))}")

    # ---- horizon-wise, persistence carried alongside the model -------------
    # The overall average hides the crossover; this resolution shows it.
    STEPS = (3, 6, 9, 12)
    header = group_header("\\multirow{2}{*}{Dataset} & \\multirow{2}{*}{Model}",
                          [f"{s * 5} min" for s in STEPS], 3, 2, HM)
    body: List[str] = []
    for i, (d_, r) in enumerate(zip(disp, roots)):
        if i:
            body.append("\\midrule")
        body.append("\\multirow{2}{*}{%s}" % d_)
        for tag, label in (("copy_last", "Persistence"),
                           (a.tag, "\\textbf{HAWFormer}")):
            cells = [" ", label]
            for s in STEPS:
                dd = agg(r, tag, HM, path=("by_horizon", f"step_{s}"))
                cells += [cell(dd.get(m) if dd else None, 2) for m in HM]
            body.append(row(cells))
    write(out, "table_horizon.tex", "@{}ll" + " ccc" * len(STEPS), header, body)

    # ---- ablation ----------------------------------------------------------
    header = group_header("\\multirow{2}{*}{Variant}", disp, 3, 1, HM)
    body = []
    for tag, label in ABLATION:
        cells, any_data = [label], False
        for r in roots:
            d = agg(r, tag, HM)
            any_data = any_data or bool(d)
            cells += [cell(d.get(m) if d else None, nd(m)) for m in HM]
        if any_data:
            body.append(row(cells))
    body.append("\\midrule")
    cells = ["\\textbf{HAWFormer}"]
    for r in roots:
        d = agg(r, a.tag, HM)
        cells += [cell(d.get(m) if d else None, nd(m)) for m in HM]
    body.append(row(cells))
    write(out, "table_ablation.tex", "@{}l" + " ccc" * nds, header, body)

    # ---- conditions --------------------------------------------------------
    CONDS = (("free", "Free-flow"), ("congested", "Congested"),
             ("incident", "Incident"))
    header = group_header("\\multirow{2}{*}{Data} & \\multirow{2}{*}{Model}",
                          [c[1] for c in CONDS], 2, 2, ("MAE", "RMSE"))
    body, first = [], True
    for d_, r in zip(disp, roots):
        rows_here = []
        for tag, label in (("copy_last", "Persistence"), ("gamma1", "$\\gamma=1$"),
                           ("no_meso", "w/o Meso"), (a.tag, "\\textbf{HAWFormer}")):
            cells, any_data = [" ", label], False
            for cond, _ in CONDS:
                d = agg(r, tag, ("MAE", "RMSE"), path=("by_condition", cond))
                any_data = any_data or bool(d)
                cells += [cell(d.get(m) if d else None, 2) for m in ("MAE", "RMSE")]
            if any_data:
                rows_here.append(row(cells))
        if not rows_here:
            continue
        if not first:
            body.append("\\midrule")
        first = False
        body.append("\\multirow{%d}{*}{%s}" % (len(rows_here), d_))
        body += rows_here
    write(out, "table_conditions.tex", "@{}ll" + " cc" * len(CONDS), header, body)

    print("\nmain.tex \\inputs these directly; recompile to pick them up.")


if __name__ == "__main__":
    main()
